version: "3"
services:
  goapp:
    build: ./goapp
    ports:
      - "38080:38080"
      - "2112:2112"
  node_exporter:
    image: prom/node-exporter:v1.6.0
    ports:
      - "9100:9100"
    volumes:
      - "/procs:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana:10.0.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
volumes:
  prometheus_data:
    driver: local
